site_name: Biosigpy
site_description: Python implementation of Biosiglib specifications for biomedical signal processing by BSICoS.
repo_url: https://github.com/BSICoS/biosigpy
repo_name: biosigpy

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            separate_signature: true
  - minify:
      minify_html: true
  - redirects

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
